### ISSUE TITLE
Latest documentation build fails to generate manual

### ISSUE THREAD

**Issue by timurgordon** [threefoldtech/3bot#152]
https://threefoldtech.github.io/web3_proxy/manual is supposed to display the manual for web3proxy.
![image](https://github.com/threefoldtech/web3_proxy/assets/31495328/b9cc52b0-9c23-4565-89a6-1479ff092359)
![image](https://github.com/threefoldtech/web3_proxy/assets/31495328/63745c8f-359f-47ab-8e4d-e59d620d0e9b)

**Comment by despiegk** [comment]
see https://github.com/freeflowuniverse/spiderlib/issues/12

**Comment by brandonpille** [comment]
I fixed the isse in the documentation that resulted in CI failing to generate the docs. But I didn't fix the fact that it silently continues execution when generating the docs failed. We should fix the doc.vsh to make the CI fail when the documentation generation failed. We want to know immediately when the generation of the documentation failed so that we can handle quickly.

**Comment by brandonpille** [comment]
> see [freeflowuniverse/spiderlib#12](https://github.com/freeflowuniverse/spiderlib/issues/12)

We are already doing this in the web3_proxy repo.
